language: node_js

cache:
  directories:
    - node_modules

notifications:
  email: false

node_js:
  - '10'
  - 'lts/*'

install:
  - travis_retry npm install

before_script:
  - npm prune

script:
  - npm test
  - npm run build

branches:
  only:
    - master