language: node_js

cache:
  directories:
    - node_modules

notifications:
  email: false

node_js:
  - 'lts/*'

install:
  - npm install

before_script:
  - npm prune

script:
  - npm test
  - npm run build

after_success:
  - npx semantic-release

branches:
  only:
    - master